apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: patches/mcp-server-replicas.yaml
  - path: patches/imagepullsecret.yaml
  - path: patches/postgres-emptydir.yaml
  - path: patches/mcp-server-probes.yaml

images:
  - name: context-cloak-mcp-server
    newName: 081006927100.dkr.ecr.us-east-1.amazonaws.com/context-cloak-mcp-server
    newTag: v3
